<?php require('template/header.phtml') ?>
<?php
if (isset($view->confirmChange)) {
    echo '<h4 style="color: darkgreen;">' . $view->confirmChange . '</h4>';
    ?>
    <div class="col-md-4">
        <h4><a href="index.php?">Login</a></h4>
    </div>
    <?php
}
else {
    if (isset($view->incorrect)) {
    echo $view->incorrect;
    }
    ?>
    <div class="container-fluid">
        <form id="postForm" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" enctype="multipart/form-data">
            <div id="profileBtn" class="row">
                <div class="col-xs-8 col-md-6">
                    <input type="button" value="Return to Profile" name="return" class="btn btn-warning" onclick="window.location.href = 'profile.php'"/>
                </div>
            </div>
            <h5 style="font-family: Arial Black;">Please fill in the fields provided appropriately:</h5>
            <div class="container-fluid">
                <div class="form-group col-md-8">
                    <input name="password" placeholder="current password here..." class="form-control" type="password"
                        <?php if (isset($_POST['password'])) {
                            echo htmlentities($_POST['password']);
                        } ?>/>
                </div>
                <div class="form-group col-md-8">
                    <input name="newPassword" placeholder="new password here..." class="form-control" type="password"
                        <?php if (isset($_POST['newPassword'])) {
                            echo htmlentities($_POST['newPassword']);
                        } ?>/>
                </div>
                <div class="form-group col-md-8">
                    <input name="confirmPassword" placeholder="confirm new password..." class="form-control" type="password"
                        <?php if (isset($_POST['confirmPassword'])) {
                            echo htmlentities($_POST['confirmPassword']);
                        } ?>/>
                </div>
                <div class="row">
                    <div class="form-group col-xs-6 col-md-offset-3">
                        <input type="submit" value="Verify Change" name="verify" class="btn btn-success"/>
                    </div>
                </div>
            </div>
            <?php
            if (isset($view->errors))
                foreach ($view->errors as $error)
                    echo '<p style="color: darkred;">' . $error . '</p>';
            ?>
        </form>
    </div>
    <?php
} ?>

<?php require('template/footer.phtml') ?>
