<?php require('template/header.phtml') ?>
<?php
if (isset($view->sentMessage)) {
    echo "<h4 style='color: darkgreen;'>" . $view->sentMessage . '</h4>';
    ?>
    <div class="col-md-4">
        <h4><a href="inbox.php?">View inbox</a></h4>
    </div>
    <div class="col-md-4">
        <h4><a href="profile.php?">View profile</a></h4>
    </div>
    <?php
}
else {
    if (isset($view->errors)) {
        foreach ($view->errors as $error) : ?>
            <li style="color: darkred"><?php echo $error; ?></li>
        <?php endforeach;
    }
    ?>
    <div class="container-fluid">
        <div class="col-md-8">
            <form id="emailForm" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
                <div class="col-xs-11 col-xs-offset-2">
                    <h4>***Create and send messages***</h4>
                </div>
                <div class="form-row">
                    <div class="form-group col-sm-8">
                        <input name="email" placeholder="<?php if (isset($view->sender))
                        {echo $view->sender;}
                        else { echo "Recipient's email here...";}
                        ?>" class="form-control" type="email"
                            <?php if (isset($_POST['email'])) {
                            echo htmlentities($_POST['email']);
                        } ?>/>
                    </div>
                    <div class="form-group col-sm-6">
                        <input name="subject" placeholder="Subject here..." class="form-control" type="text"
                            <?php if (isset($_POST['subject'])) {
                                echo htmlentities($_POST['subject']);
                            } ?>/>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-12 ">
                        <textarea name="content" cols="40" rows="10" class="form-control"
                                  placeholder="Content here..."
                            <?php if (isset($_POST['content'])) {
                            echo htmlentities($_POST['content']);
                        } ?>></textarea>
                    </div>
                </div>
                <div class="form-group col-xs-5">
                    <input type="button" value="Cancel" name="cancel" class="btn btn-secondary" onclick="window.location.href = 'inbox.php'"/>
                </div>
                <div class="form-group col-xs-5 ">
                    <input type="submit" value="send" name="send" class="btn btn-primary"/>
                </div>
            </form>
        </div>
    </div> <?php
} ?>
<?php require('template/footer.phtml') ?>