<?php require('template/header.phtml') ?>
<?php
if (isset($view->insertReply)) {
    echo '<h4 style="color: darkgreen">' . $view->insertReply . '</h4>';
    ?><div class="col-md-4"><h4><a href="reply.php?">View Post</a></h4></div><?php
}
else { ?>
    <div id="postSubject">
        <h3 style="font-family: Arial Black;">
            <?php
            if (isset($view->postSubject)) {
                echo $view->postSubject;
            }
            ?>
        </h3>
        <p>
            <?php
            if (isset($view->noComments)) {
                echo $view->noComments;
            }
            ?>
        </p>
    </div>

    <div class="form-group col-xs-6 col-md-8" >
        <input type="button" value="Return" name="return" class="btn btn-warning" onclick="window.location.href = 'post.php'"/>
    </div>
    <div class="container-fluid">
        <form id="ReplyForm" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
            <?php
            if (isset($view->comments)) {
                foreach ($view->comments as $comments) {
                    if (isset($_SESSION['uname'])) {
                        echo '<div class="centered-form col-xs-8 col-md-6 col-md-offset-1"><div id="replyBox" class="panel panel-default"><div class="panel-body">' .
                            $comments->getReplyComment() . '<br/>' . $comments->getReplyDate() . '<div id="userPost">' . '<img src="images/' . $comments->getPhotoName() . '" width="50" height="50" alt="" />' .
                            '<br/>' . $comments->getUsername() . '</div>' .
                            '</div></div></div>';
                    }
                    else {
                        echo '<div class="centered-form col-xs-8 col-md-6 col-md-offset-1"><div id="replyBox" class="panel panel-default"><div class="panel-body">' .
                            $comments->getReplyComment() . '<br/>' . $comments->getReplyDate() . '<div id="userPost">' . $comments->getUsername() . '</div>' .
                            '</div></div></div>';
                    }

                }
            }
            ?>
        </form>
    </div>
    <?php
    if (isset($_SESSION['uname'])) {
        if (isset($view->error)) {
            echo "<li style='color: darkred'>" . $view->error . "</li>";
        }
        ?>
        <div class="container-fluid">
            <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
                <div class="form-row">
                    <div class="form-group col-md-6 col-md-offset-3">
                <textarea name="comment" cols="40" rows="10" class="form-control" placeholder="Comments here..."
                <?php if (isset($_POST['comment'])) {
                    echo htmlentities($_POST['comment']);
                } ?>></textarea>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-xs-8 col-md-2 col-md-offset-4">
                        <input type="reset" value="Clear" name="clear" class="btn btn-secondary"/>
                    </div>
                    <div class="col-xs-2 col-md-1 col-md-offset-1">
                        <input type="submit" value="Reply" name="reply" class="btn btn-primary"/>
                    </div>
                </div>
            </form>
        </div>
        <?php
    } ?>
    <div class="container-fluid">
        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="get">
            <ul class="pagination">
                <?php
                $totalPages = $view->numberOfPages;
                if (isset($_GET['pageNum'])) {
                    $pageNum = $_GET['pageNum'];
                } else {
                    $pageNum = 1;
                }
                ?>
                <li><a href="?pageNum=1">First</a></li>
                <li class="<?php
                if ($pageNum <= 1) {
                    echo 'disabled';
                } ?>">
                    <a href="<?php
                    if ($pageNum <= 1) {
                        echo '#';
                    } else {
                        echo "?pageNum=" . ($pageNum - 1);
                    } ?>">Prev</a></li>
                <li class="<?php
                if ($pageNum >= $totalPages) {
                    echo 'disabled';
                } ?>">
                    <a href="<?php
                    if ($pageNum >= $totalPages) {
                        echo '#';
                    } else {
                        echo "?pageNum=" . ($pageNum + 1);
                    } ?>">Next</a>
                </li>
                <li><a href="?pageNum=<?php echo $totalPages; ?>">Last</a></li>
            </ul>
        </form>
    </div>
    <?php
} ?>



<?php require('template/footer.phtml') ?>
