<?php require('template/header.phtml') ?>
<?php
if (isset($view->createTopic)) {
    echo "<h4 style='color: darkgreen'>" . $view->createTopic . "</h4>" ;
    ?>
    <div class="col-md-4">
        <h4><a href="index.php?">View Topics</a></h4>
    </div>
    <?php
}
else {
    ?>
    <h4 style="font-family: Arial Black;">You can create new topic here</h4>
    <div class="container-fluid">
        <form id="TopicForm" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
            <?php
            if (isset($view->errors)) {
                foreach ($view->errors as $error) : ?>
                    <li style="color: darkred"><?php echo $error; ?></li>
                <?php endforeach;
            }
            ?>
            <div class="form-row">
                <div class="form-group col-md-8">
                    <input name="title" placeholder="Topic title..." class="form-control" type="text"
                        <?php if (isset($_POST['title'])) {
                            echo htmlentities($_POST['title']);
                        } ?>/>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12 ">
                <textarea name="description" cols="40" rows="10" class="form-control" placeholder="Description..."
                <?php if (isset($_POST['description'])) {
                    echo ($_POST['description']);
                } ?>></textarea>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-xs-6 col-md-5">
                    <input type="button" value="Return" name="return" class="btn btn-secondary" onclick="window.location.href = 'index.php'"/>
                </div>
                <div class="form-group col-xs-6 col-md-2">
                    <input type="submit" value="Create Topic" name="createTopic" class="btn btn-success"/>
                </div>
            </div>
        </form>
    </div>
    <?php
} ?>
<?php require_once ('template/footer.phtml') ?>
