<?php require('template/header.phtml') ?>
<?php
if (isset($view->topicRemoved)) {
    echo "<h4 style='color: darkred;'>" . $view->topicRemoved . '</h4>';
    ?>
    <div class="col-md-4">
        <h4><a href="profile.php?">View my watch list</a></h4>
    </div>
    <div class="col-md-4">
        <h4><a href="index.php?">View all topics</a></h4>
    </div>
    <?php
}
 ?>

<?php require('template/footer.phtml') ?>
